### ISSUE TITLE
Scrum Report #2

### ISSUE THREAD

**Issue by mandywan** [kenhyj/Traceify#20]
What did you work on this past iteration (2 weeks)?

What were any major issues/challenges you ran into?

What do you plan to work on for this coming iteration (2 weeks)?

**Comment by kenhyj** [comment]
**1.** In this past iteration, I worked with the front end design with chaoyu to resemble our prototype sketches, and proceeded to start with the symptom checker along with using redux on the symptom checker component

**2.** A major issue I ran into was the fact that despite setting up the reducer and actions right, 
`import reducers from './redux' ` from src/index.js
had to be corrected to 
`import reducers from './redux/reducers' `
it seemed really trivial in hindsight but none of the states could be accessed (returned undefined). 

**3.** In addition to debugging our current project, I plan on finishing off the requirements with the symptom checker by the end of this week then proceed to creating mock data.

**Comment by kessris** [comment]
CS ID: k0b0b

1. I set up the project with create-react-app, set-up redux, organized Router in a conventional way and set-up logo for example to navigate to a certain page set up by Router using <Link>.

2. Not in particular.

3. Set-up and populate the database. Get OAuth working for the Admin users. We will also discuss further to see if there's additional tasks to be assigned during our group meeting.

**Comment by mandywan** [comment]
csid: d2e2b

1. This past iteration I...
- set up Google Maps JavaScript API
- created Maps component
- created Financial Help page
- created reusable cards (currently used in financial help page only) via Material UI

2. I had to try out a few different npm packages for Google Maps since the first one I used was not maintained. I found one that was updated 3 days prior to my implementation and used that one instead.

3. I plan to make the following components for maps: heat map, markers, neighbourhood polygons (maybe).  I will make mock data or retrieve this from an API and store this in our database.

**Comment by ChaoyuXiang** [comment]
csid : l0y2b
1. In this sprint, I created header component with Material UI and added basic styling to it. Also I finished thank you page as the landing page and put style to it.
2. The major challenge i had is to dealing with JSS styling inside js.
3. I plan to make thank you page as Modal and put more styling to other components. Also focus on redux part.
